# Generated by Django 3.2.12 on 2022-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
