# Generated by Django 3.2.12 on 2022-02-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dress', 'dress'), ('bag', 'bag'), ('shirt', 'shirt'), ('cloth', 'cloth'), ('jacket', 'jacket')], default='dress', max_length=100),
            preserve_default=False,
        ),
    ]
