# Generated by Django 3.2.12 on 2022-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
