# Generated by Django 3.2.12 on 2022-03-16 18:05

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.UUIDField(default=product.models.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='product.order')),
            ],
        ),
    ]
