# Generated by Django 3.2.12 on 2022-03-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_billingaddress'),
        ('product', '0016_subscribe'),
    ]

    operations = [
    ]
